# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(998, 571)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(370, 10, 331, 101))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 330, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(600, 150, 71, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(600, 320, 71, 20))
        self.label_5.setObjectName("label_5")
        self.txt_plaintext = QtWidgets.QTextEdit(Dialog)
        self.txt_plaintext.setGeometry(QtCore.QRect(130, 130, 321, 71))
        self.txt_plaintext.setObjectName("txt_plaintext")
        self.txt_CurrentText = QtWidgets.QTextEdit(Dialog)
        self.txt_CurrentText.setGeometry(QtCore.QRect(120, 300, 321, 71))
        self.txt_CurrentText.setObjectName("txt_CurrentText")
        self.txt_Information = QtWidgets.QTextEdit(Dialog)
        self.txt_Information.setGeometry(QtCore.QRect(660, 130, 321, 71))
        self.txt_Information.setObjectName("txt_Information")
        self.txt_Siganture = QtWidgets.QTextEdit(Dialog)
        self.txt_Siganture.setGeometry(QtCore.QRect(660, 290, 321, 71))
        self.txt_Siganture.setObjectName("txt_Siganture")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 460, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 460, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(660, 450, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(800, 450, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">RSA CIPHER</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Plain text"))
        self.label_3.setText(_translate("Dialog", "Current text"))
        self.label_4.setText(_translate("Dialog", "Information"))
        self.label_5.setText(_translate("Dialog", "Signature"))
        self.pushButton.setText(_translate("Dialog", "Encrypy"))
        self.pushButton_2.setText(_translate("Dialog", "Decrypt"))
        self.pushButton_3.setText(_translate("Dialog", "Sign"))
        self.pushButton_4.setText(_translate("Dialog", "Verity"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
